/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedTradingRouteImport } from './routes/_authenticated/trading'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMarketsRouteImport } from './routes/_authenticated/markets'
import { Route as AuthenticatedMarketOpsRouteImport } from './routes/_authenticated/market-ops'
import { Route as AuthenticatedFuturesRouteImport } from './routes/_authenticated/futures'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin-withdrawals'
import { Route as AuthenticatedAdminDepositsRouteImport } from './routes/_authenticated/admin-deposits'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradingRoute = AuthenticatedTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketsRoute = AuthenticatedMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketOpsRoute = AuthenticatedMarketOpsRouteImport.update({
  id: '/market-ops',
  path: '/market-ops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFuturesRoute = AuthenticatedFuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/admin-withdrawals',
    path: '/admin-withdrawals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDepositsRoute =
  AuthenticatedAdminDepositsRouteImport.update({
    id: '/admin-deposits',
    path: '/admin-deposits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin-withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/futures': typeof AuthenticatedFuturesRoute
  '/market-ops': typeof AuthenticatedMarketOpsRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/trading': typeof AuthenticatedTradingRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin-withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/futures': typeof AuthenticatedFuturesRoute
  '/market-ops': typeof AuthenticatedMarketOpsRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/trading': typeof AuthenticatedTradingRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-deposits': typeof AuthenticatedAdminDepositsRoute
  '/_authenticated/admin-withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/futures': typeof AuthenticatedFuturesRoute
  '/_authenticated/market-ops': typeof AuthenticatedMarketOpsRoute
  '/_authenticated/markets': typeof AuthenticatedMarketsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/trading': typeof AuthenticatedTradingRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/admin-deposits'
    | '/admin-withdrawals'
    | '/dashboard'
    | '/deposit'
    | '/futures'
    | '/market-ops'
    | '/markets'
    | '/profile'
    | '/trading'
    | '/wallets'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin-deposits'
    | '/admin-withdrawals'
    | '/dashboard'
    | '/deposit'
    | '/futures'
    | '/market-ops'
    | '/markets'
    | '/profile'
    | '/trading'
    | '/wallets'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/admin-deposits'
    | '/_authenticated/admin-withdrawals'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposit'
    | '/_authenticated/futures'
    | '/_authenticated/market-ops'
    | '/_authenticated/markets'
    | '/_authenticated/profile'
    | '/_authenticated/trading'
    | '/_authenticated/wallets'
    | '/_authenticated/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trading': {
      id: '/_authenticated/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof AuthenticatedTradingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/markets': {
      id: '/_authenticated/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AuthenticatedMarketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/market-ops': {
      id: '/_authenticated/market-ops'
      path: '/market-ops'
      fullPath: '/market-ops'
      preLoaderRoute: typeof AuthenticatedMarketOpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/futures': {
      id: '/_authenticated/futures'
      path: '/futures'
      fullPath: '/futures'
      preLoaderRoute: typeof AuthenticatedFuturesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-withdrawals': {
      id: '/_authenticated/admin-withdrawals'
      path: '/admin-withdrawals'
      fullPath: '/admin-withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-deposits': {
      id: '/_authenticated/admin-deposits'
      path: '/admin-deposits'
      fullPath: '/admin-deposits'
      preLoaderRoute: typeof AuthenticatedAdminDepositsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminDepositsRoute: typeof AuthenticatedAdminDepositsRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedFuturesRoute: typeof AuthenticatedFuturesRoute
  AuthenticatedMarketOpsRoute: typeof AuthenticatedMarketOpsRoute
  AuthenticatedMarketsRoute: typeof AuthenticatedMarketsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTradingRoute: typeof AuthenticatedTradingRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminDepositsRoute: AuthenticatedAdminDepositsRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedFuturesRoute: AuthenticatedFuturesRoute,
  AuthenticatedMarketOpsRoute: AuthenticatedMarketOpsRoute,
  AuthenticatedMarketsRoute: AuthenticatedMarketsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTradingRoute: AuthenticatedTradingRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
